### ISSUE TITLE
Add subuser support

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#42] opened 2015-11-05 16:13 UTC
This may been need in order to add this project to TravisCI. If we can't get a dedicated Joyent account for testing against Manta, then we may need to create a subuser in order to use an existing account with minimal privileges.

**Comment by phillipross** [comment] 2015-11-17 07:35
I don't believe that there are any code changes necessary to make the java-manta client code function with a subuser.  I do believe that we still may need to setup a subuser within an existing account w/ minimal privileges, but would be part of the CI setup.

I'm closing this issue as a duplicate of https://github.com/joyent/java-manta/issues/18 and adding a note to the other issue about the idea of subuser configuration.

**Comment by dekobon** [comment] 2015-11-17 07:48
At the very least I would like to add tests verifying that is it working.
Also, I want to support the subuser env var.

**Comment by phillipross** [comment] 2015-11-17 18:07
I'll have to take another look, but when I was reviewing documentation the past few weeks, it looked like they did away with the SUBUSER environment variable in the CLI and now everything is driven off of a flat namespace of accounts.  I'll take a closer look.

**Comment by dekobon** [comment] 2015-11-17 18:09
I didn't know that they moved away from the environment variable. That
makes sense.

On Tue, Nov 17, 2015 at 10:07 AM, Phillip Ross <notifications@github.com>
wrote:

> I'll have to take another look, but when I was reviewing documentation the
> past few weeks, it looked like they did away with the SUBUSER environment
> variable in the CLI and now everything is driven off of a flat namespace of
> accounts. I'll take a closer look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/java-manta/issues/42#issuecomment-157455746>.
>



-- 
-Elijah

**Closed** 2015-11-19 19:39 UTC
Labels: enhancement
