### ISSUE TITLE
TCPSocketConnectionTimeoutIT error running verify

### ISSUE THREAD

**Issue by russelldb** [joyent/java-manta#515] opened 2019-05-17 16:44 UTC
When I run  

```
MANTA_URL=https://manta.garage.local mvn -Dmanta.user=java_test 
-Dmanta.key_id=SHA256:vOlOMddoqBTCaCrO1BQTc0D1Zi+DzfvxHlZyg9JYvxY
-Dmanta.key_path=/home/russell/dev/joyent/repos/java-manta/java_id_rsa  -e verify
```
 I get

```
Cannot instantiate class com.joyent.manta.http.TCPSocketConnectionTimeoutIT
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

```

**Comment by nairashwin952013** [comment] 2019-05-17 22:23
@russelldb 

'/* This *should* be an invalid IP/port. 192.0.2.0/24
                           is intended to be reserved as TEST-NET-1 thus giving
                           us an invalid/unreachable MANTA_URL value. */
                        .setMantaURL("https://192.0.2.0:9324"),'

Did you notice this comment written above setting `MANTA_URL` for this particular `integration-test` ?

**Comment by nairashwin952013** [comment] 2019-05-17 23:39
This `Issue` is currently being tracked by #517.

**Comment by cburroughs** [comment] 2019-05-20 21:21
The "dump" file has a slightly fuller stack trace
```
[root@52165b86-a1d3-6a0e-96c0-cea209198845 /var/tmp/tmp-manta-nightly-sdk]# cat java-manta-it/target/failsafe-reports/2019-05-20T20-35-18_863-jvmRun1.dump 
# Created on 2019-05-20T20:35:21.491
org.testng.TestNGException: 
Cannot instantiate class com.joyent.manta.http.TCPSocketConnectionTimeoutIT
        at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
        at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
        at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
        at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
        at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
        at org.testng.TestClass.getInstances(TestClass.java:95)
        at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
        at org.testng.TestClass.init(TestClass.java:73)
        at org.testng.TestClass.<init>(TestClass.java:38)
        at org.testng.TestRunner.initMethods(TestRunner.java:389)
        at org.testng.TestRunner.init(TestRunner.java:271)
        at org.testng.TestRunner.init(TestRunner.java:241)
        at org.testng.TestRunner.<init>(TestRunner.java:167)
        at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
        at org.testng.SuiteRunner.init(SuiteRunner.java:260)
        at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
        at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
        at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:24)
        ... 27 more
Caused by: com.joyent.manta.exception.ConfigurationException: Given fingerprint c4:13:be:5c:fe:a7:53:ce:c2:03:53:2b:f7:47:14:e2 does not match expected key MD5:de:e7:73:9a:b0:91:31:3e:72:8d:9f:62:ca:58:a2:ec SHA256:2XCGHtsnTro2MGqoVQHgXSS/ai12yQHrGFrN12YUPpA
Exception Context:
        [1:mantaSdkVersion=3.4.1-SNAPSHOT]
---------------------------------
        at com.joyent.manta.config.KeyPairFactory.createKeyPair(KeyPairFactory.java:85)
        at com.joyent.manta.config.AuthAwareConfigContext.doLoad(AuthAwareConfigContext.java:107)
        at com.joyent.manta.config.AuthAwareConfigContext.reload(AuthAwareConfigContext.java:88)
        at com.joyent.manta.config.AuthAwareConfigContext.<init>(AuthAwareConfigContext.java:64)
        at com.joyent.manta.http.TCPSocketConnectionTimeoutIT.<init>(TCPSocketConnectionTimeoutIT.java:37)
        ... 32 more
```

**Comment by nairashwin952013** [comment] 2019-05-20 22:15
> The "dump" file has a slightly fuller stack trace
> 
> ```
> [root@52165b86-a1d3-6a0e-96c0-cea209198845 /var/tmp/tmp-manta-nightly-sdk]# cat java-manta-it/target/failsafe-reports/2019-05-20T20-35-18_863-jvmRun1.dump 
> # Created on 2019-05-20T20:35:21.491
> org.testng.TestNGException: 
> Cannot instantiate class com.joyent.manta.http.TCPSocketConnectionTimeoutIT
>         at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
>         at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
>         at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
>         at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
>         at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
>         at org.testng.TestClass.getInstances(TestClass.java:95)
>         at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
>         at org.testng.TestClass.init(TestClass.java:73)
>         at org.testng.TestClass.<init>(TestClass.java:38)
>         at org.testng.TestRunner.initMethods(TestRunner.java:389)
>         at org.testng.TestRunner.init(TestRunner.java:271)
>         at org.testng.TestRunner.init(TestRunner.java:241)
>         at org.testng.TestRunner.<init>(TestRunner.java:167)
>         at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
>         at org.testng.SuiteRunner.init(SuiteRunner.java:260)
>         at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
>         at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
>         at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
>         at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
>         at org.testng.TestNG.runSuites(TestNG.java:1049)
>         at org.testng.TestNG.run(TestNG.java:1017)
>         at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
>         at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
>         at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
>         at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
>         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
>         at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
> Caused by: java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:24)
>         ... 27 more
> Caused by: com.joyent.manta.exception.ConfigurationException: Given fingerprint c4:13:be:5c:fe:a7:53:ce:c2:03:53:2b:f7:47:14:e2 does not match expected key MD5:de:e7:73:9a:b0:91:31:3e:72:8d:9f:62:ca:58:a2:ec SHA256:2XCGHtsnTro2MGqoVQHgXSS/ai12yQHrGFrN12YUPpA
> Exception Context:
>         [1:mantaSdkVersion=3.4.1-SNAPSHOT]
> ---------------------------------
>         at com.joyent.manta.config.KeyPairFactory.createKeyPair(KeyPairFactory.java:85)
>         at com.joyent.manta.config.AuthAwareConfigContext.doLoad(AuthAwareConfigContext.java:107)
>         at com.joyent.manta.config.AuthAwareConfigContext.reload(AuthAwareConfigContext.java:88)
>         at com.joyent.manta.config.AuthAwareConfigContext.<init>(AuthAwareConfigContext.java:64)
>         at com.joyent.manta.http.TCPSocketConnectionTimeoutIT.<init>(TCPSocketConnectionTimeoutIT.java:37)
>         ... 32 more
> ```

Chris did you perform this test after incorporating the changes introduced by #517 ?

**Comment by cburroughs** [comment] 2019-05-21 19:14
The above was from master.

I think I understand what is getting on a little better what is going on.  This error appears to occur when `MANTA_KEY_ID` is not set correctly.  For example, on my workstation the following reproduced the problem (with my key in the default location).
```
MANTA_URL=https://us-east.manta.joyent.com
MANTA_KEY_ID=<RANDOM_PERMUtAtION>
MANTA_USER=cburroughs
```

So while I think it is okay that this test "fails", the error (jvm dump) is wildly misleading.

@russelldb do you hit this when using env vars (like node-manta?)

**Comment by russelldb** [comment] 2019-05-22 10:48
I'm not sure what is happening here at all. I've looked at my config and the key id matches the key I specify.

I'm using `mvn -Dmanta.X=VAL` as that is the only way I could get the tests to pick up my config. I have env vars that work for node-manta, but they are not detected/used by the `mvn verify` command.

the full command is:

` mvn -Dmanta.url=https://manta.garage.local -Dmanta.user=java_test -Dmanta.key_id=SHA256:vOlOMddoqBTCaCrO1BQTc0D1Zi+DzfvxHlZyg9JYvxY -Dmanta.key_path=/home/russell/dev/joyent/repos/java-manta/java_id_rsa  verify`

if I run `ssh-keygen -lf java_id_rsa` it outputs `SHA256:vOlOMddoqBTCaCrO1BQTc0D1Zi+DzfvxHlZyg9JYvxY`

**Comment by russelldb** [comment] 2019-05-22 10:50
I have to say, despite following instructions, I still have no idea how to get either maven or intelliJ to use my config settings, except to create test run configs in IntelliJ for individual tests.

**Comment by russelldb** [comment] 2019-05-22 10:58
In fact, this is odd:-

```
Caused by: com.joyent.manta.exception.ConfigurationException: Given fingerprint SHA256:N5Qi3xOV9WweY0i1kohPcdRrzAMwIQ6SxIST8G4bJTo does not match expected key 
MD5:a2:65:bf:30:3f:d5:ab:17:c2:11:61:b2:3c:5b:20:0e SHA256:vOlOMddoqBTCaCrO1BQTc0D1Zi+DzfvxHlZyg9JYvxY
Exception Context:
```
when the "given fingerprint" is 

`-Dmanta.key_id=SHA256:vOlOMddoqBTCaCrO1BQTc0D1Zi+DzfvxHlZyg9JYvxY` That other fingerprint is from the environment variables. Am I to unset the env vars first? Do env vars trump -D type system properties?

**Comment by russelldb** [comment] 2019-05-22 10:59
What should be in the key id? Just the sha? Just the md5? Both?

**Comment by russelldb** [comment] 2019-05-22 11:03
OK, so if I set the env var MANTA_KEY_ID to the md5 I get further along. Sorry, this has all been one big adventure in config from me (an adventure where I repeatedly get it wrong)

**Comment by russelldb** [comment] 2019-05-22 11:09
I am surprised that env vars (more general) trump -Dmanta.url system prop values (more specific). Are they supposed to? Have I failed to read some bit of documentation?

**Comment by cburroughs** [comment] 2019-05-22 20:28
I don't think we should close this issue yet.  Even if the "real" problem was configuration, I think we can provide a better error message that doesn't confuse (multiple!) people for days.

**Comment by russelldb** [comment] 2019-05-22 21:18
Fair play. I was going to open a new one. But re-open is good too, sorry for the hasty close. I think another equally confusing issue is that `-Dmanta.x=y` properties set explicitly _don't_ override implicit environment variables, or is that just me, and my misguided expectations? Should I open an issue for that?

**Comment by nairashwin952013** [comment] 2019-05-22 21:25
> Fair play. I was going to open a new one. But re-open is good too, sorry for the hasty close. I think another equally confusing issue is that `-Dmanta.x=y` properties set explicitly _don't_ override implicit environment variables, or is that just me, and my misguided expectations? Should I open an issue for that?

I don't this that's a bug because it works fine for me, it might have something to do with your setup in `IntelliJ` or the way your `env` is set up for the `SDK`.

**Comment by russelldb** [comment] 2019-05-23 06:51
This is on the cli. I have MANTA_X vars in my environment, and I call `mvn -Dmanta.x=y` on the cli, and the env vars are preferred to the `-D` properties. Nothing to do with IntelliJ. I'm asking if you think that is correct? My reasoning that it is  a bug is that the env vars are silent and implicit, and I took the trouble to explicitly specify `-D` props and they're ignored.

A good analogy would be this: I have env vars in my .bashrc, for example `MANTA_USER=russell.brown` but when I do joyent scrum I run `MANTA_USER=Joyent_Dev scrum -d my_file`

I override the implicit env with an explicit value. This is why I was surprised to that running the iTests from the cli with maven ignored the `-Dmanta.key_id` in favour of the `MANTA_KEY_ID` in my .bashrc.

Does that make sense?

**Comment by cburroughs** [comment] 2019-05-23 17:36
My naive expectation as a user is that system properties would take precedence over environmental variables.  `SystemSettingsConfigContext` says:
```
     * Populate configuration from defaults, environment variables and system
     * properties.
```
which also at least implies that order, although that isn't what the code does.  There are backwards compatibility considerations to changing that (or adding `SystemSettingsWithDifferrentPrecedenceConfigContext`?), so a separate issue is probably in order.

**Comment by russelldb** [comment] 2019-05-24 07:23
Thanks @cburroughs, that makes sense. Will open a new issue.

Should we close this one now? Or still improvements required to error handling, I guess?

**Comment by jlevon** [comment] 2019-11-15 11:11
Filed #556 for the usability case; closing this.

**Closed by jlevon** 2019-11-15 11:11 UTC
Labels: test-bug
